base_url = "https://groutoutlook.github.io/"

[[top_links]]
title = "Homepage"
url = "https://groutoutlook.github.io/"

[[top_links]]
title = "TILs"
url = "https://groutoutlook.github.io/site/index.html"
